using System.Security.Claims;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using MunicipalPlatform.Api.Infrastructure.Persistence;
using MunicipalPlatform.Api.Modules.Gazette.Domain;
using MunicipalPlatform.Api.Modules.Gazette.Services;
using MunicipalPlatform.Api.Modules.Operations.Domain;
using MunicipalPlatform.Api.Platform.Tenancy;

namespace MunicipalPlatform.Api.Modules.Gazette;

public static class GazetteCompositionEndpoints
{
    public static IEndpointRouteBuilder MapGazetteCompositionEndpoints(this IEndpointRouteBuilder endpoints)
    {
        var group = endpoints.MapGroup("/api/v1/admin/gazette/{editionId:guid}/composition").WithTags("Admin", "Gazette", "Composition").RequireAuthorization(p => p.RequireClaim("capability", "gazette.write"));
        group.MapGet("/", GetAsync); group.MapPost("/sections", AddSectionAsync); group.MapPut("/sections/{sectionId:guid}", UpdateSectionAsync); group.MapPost("/sections/{sectionId:guid}/acts", AddActAsync); group.MapPut("/acts/{actId:guid}", UpdateActAsync); return endpoints;
    }
    private static async Task<IResult> GetAsync(Guid editionId, ApplicationDbContext db, CancellationToken ct){var edition=await db.GazetteEditions.AsNoTracking().SingleOrDefaultAsync(x=>x.Id==editionId,ct);if(edition is null)return Results.NotFound();var sections=await db.GazetteSections.AsNoTracking().Where(x=>x.GazetteEditionId==editionId).OrderBy(x=>x.DisplayOrder).ToListAsync(ct);var acts=await db.GazetteActs.AsNoTracking().Where(x=>x.GazetteEditionId==editionId).OrderBy(x=>x.DisplayOrder).ToListAsync(ct);return Results.Ok(new{edition.Id,edition.Number,edition.Year,edition.Status,sections=sections.Select(s=>new{s.Id,s.Title,s.DisplayOrder,acts=acts.Where(a=>a.GazetteSectionId==s.Id)})});}
    private static async Task<IResult> AddSectionAsync(Guid editionId,SectionRequest request,ClaimsPrincipal principal,HttpContext context,ApplicationDbContext db,TenantContext tenant,CancellationToken ct){var edition=await EditableEdition(editionId,db,ct);if(edition is null)return Results.Conflict(new{title="Edição inexistente ou composição imutável no estado atual."});var section=new GazetteSection(tenant.RequireMunicipalityId(),editionId,request.Title,request.DisplayOrder);db.GazetteSections.Add(section);AddAudit(db,tenant,principal,context,"gazette.section.created",section.Id,new{editionId,section.Title,section.DisplayOrder});await db.SaveChangesAsync(ct);return Results.Created($"/api/v1/admin/gazette/{editionId}/composition/sections/{section.Id}",section);}
    private static async Task<IResult> UpdateSectionAsync(Guid editionId,Guid sectionId,SectionRequest request,ClaimsPrincipal principal,HttpContext context,ApplicationDbContext db,TenantContext tenant,GazetteDocumentService documents,CancellationToken ct){var edition=await EditableEdition(editionId,db,ct);if(edition is null)return Results.Conflict(new{title="Composição imutável no estado atual."});var section=await db.GazetteSections.SingleOrDefaultAsync(x=>x.Id==sectionId&&x.GazetteEditionId==editionId,ct);if(section is null)return Results.NotFound();section.Update(request.Title,request.DisplayOrder);await RebuildSnapshotAsync(edition,RequireActor(principal),db,documents,ct);AddAudit(db,tenant,principal,context,"gazette.section.updated",section.Id,new{section.Title,section.DisplayOrder});await db.SaveChangesAsync(ct);return Results.Ok(section);}
    private static async Task<IResult> AddActAsync(Guid editionId,Guid sectionId,ActRequest request,ClaimsPrincipal principal,HttpContext context,ApplicationDbContext db,TenantContext tenant,GazetteDocumentService documents,CancellationToken ct){var edition=await EditableEdition(editionId,db,ct);if(edition is null)return Results.Conflict(new{title="Composição imutável no estado atual."});if(!await db.GazetteSections.AnyAsync(x=>x.Id==sectionId&&x.GazetteEditionId==editionId,ct))return Results.NotFound();if(!DateOnly.TryParse(request.ActDate,out var actDate))return Results.ValidationProblem(new Dictionary<string,string[]>{{"actDate",["Data inválida. Use yyyy-MM-dd."]}});var act=new GazetteAct(tenant.RequireMunicipalityId(),editionId,sectionId,request.ActType,request.Number,request.Year,request.Title,request.Body,request.Issuer,actDate,request.DisplayOrder);db.GazetteActs.Add(act);await db.SaveChangesAsync(ct);await RebuildSnapshotAsync(edition,RequireActor(principal),db,documents,ct);AddAudit(db,tenant,principal,context,"gazette.act.created",act.Id,new{editionId,sectionId,act.ActType,act.Number,act.Year,act.Title});await db.SaveChangesAsync(ct);return Results.Created($"/api/v1/admin/gazette/{editionId}/composition/acts/{act.Id}",act);}
    private static async Task<IResult> UpdateActAsync(Guid editionId,Guid actId,ActRequest request,ClaimsPrincipal principal,HttpContext context,ApplicationDbContext db,TenantContext tenant,GazetteDocumentService documents,CancellationToken ct){var edition=await EditableEdition(editionId,db,ct);if(edition is null)return Results.Conflict(new{title="Composição imutável no estado atual."});var act=await db.GazetteActs.SingleOrDefaultAsync(x=>x.Id==actId&&x.GazetteEditionId==editionId,ct);if(act is null)return Results.NotFound();if(!DateOnly.TryParse(request.ActDate,out var actDate))return Results.ValidationProblem(new Dictionary<string,string[]>{{"actDate",["Data inválida. Use yyyy-MM-dd."]}});act.Update(request.ActType,request.Number,request.Year,request.Title,request.Body,request.Issuer,actDate,request.DisplayOrder);await RebuildSnapshotAsync(edition,RequireActor(principal),db,documents,ct);AddAudit(db,tenant,principal,context,"gazette.act.updated",act.Id,new{act.ActType,act.Number,act.Year,act.Title});await db.SaveChangesAsync(ct);return Results.Ok(act);}
    private static Task<GazetteEdition?> EditableEdition(Guid id,ApplicationDbContext db,CancellationToken ct)=>db.GazetteEditions.SingleOrDefaultAsync(x=>x.Id==id&&(x.Status==GazetteStatus.Draft||x.Status==GazetteStatus.Review),ct);
    private static async Task RebuildSnapshotAsync(GazetteEdition edition,Guid actor,ApplicationDbContext db,GazetteDocumentService documents,CancellationToken ct){var sections=await db.GazetteSections.Where(x=>x.GazetteEditionId==edition.Id).OrderBy(x=>x.DisplayOrder).ToListAsync(ct);var acts=await db.GazetteActs.Where(x=>x.GazetteEditionId==edition.Id).OrderBy(x=>x.DisplayOrder).ToListAsync(ct);var composed=sections.Select(section=>new GazetteSectionInput(section.Title,acts.Where(a=>a.GazetteSectionId==section.Id).Select(a=>new GazetteActInput(a.Title,a.Body,a.Issuer,$"{a.ActType} {a.Number}/{a.Year}".Trim())).ToArray())).Where(section=>section.Acts.Count>0).ToArray();if(composed.Length>0)edition.SetComposition(documents.NormalizeComposition(new GazetteComposition(composed)),actor,DateTimeOffset.UtcNow);}
    private static void AddAudit(ApplicationDbContext db,TenantContext tenant,ClaimsPrincipal principal,HttpContext context,string action,Guid id,object diff)=>db.AuditEvents.Add(new AuditEvent(tenant.RequireMunicipalityId(),RequireActor(principal),action,"GazetteComposition",id.ToString(),JsonSerializer.Serialize(diff),context.TraceIdentifier));
    private static Guid RequireActor(ClaimsPrincipal p)=>Guid.TryParse(p.FindFirstValue(ClaimTypes.NameIdentifier),out var id)?id:throw new InvalidOperationException("Sessão inválida.");
    public sealed record SectionRequest(string Title,int DisplayOrder); public sealed record ActRequest(string ActType,string? Number,int? Year,string Title,string Body,string Issuer,string ActDate,int DisplayOrder);
}
