import { expect, test } from "@playwright/test";

test("POC principal: cidadão, CMS, Diário e Ouvidoria",async({page})=>{
  const password=process.env.DEMO_PASSWORD;if(!password)throw new Error("DEMO_PASSWORD é obrigatório para a POC automatizada.");
  await page.goto("/");await expect(page.getByRole("heading",{name:/Olá! O que você precisa/i})).toBeVisible();
  await page.goto("/servicos");await page.getByRole("link",{name:/Emitir guia do IPTU/i}).click();await expect(page.getByRole("heading",{name:/Emitir guia do IPTU/i})).toBeVisible();

  await page.goto("/admin/login");await page.getByLabel("Usuário").fill("admin.demo");await page.getByLabel("Senha").fill(password);await page.getByRole("button",{name:"Entrar"}).click();await page.waitForURL(/\/admin$/);await expect(page.getByRole("heading",{name:/Bom dia/i})).toBeVisible();

  const suffix=Date.now().toString().slice(-8);const slug=`poc-noticia-${suffix}`;
  await page.goto("/admin/noticias/nova");await page.getByLabel("Título").fill(`[DEMONSTRAÇÃO] Notícia POC ${suffix}`);await page.getByLabel("Slug").fill(slug);await page.getByLabel("Linha fina").fill("Publicação sintética criada pelo teste E2E.");await page.getByLabel("Conteúdo").fill("Conteúdo de demonstração sem valor de comunicado oficial. Este texto comprova persistência e workflow editorial.");await page.getByRole("button",{name:"Criar rascunho"}).click();await expect(page.getByText(/Rascunho salvo no servidor/)).toBeVisible();await page.getByRole("button",{name:"Enviar para revisão"}).click();await expect(page.getByText(/Ação “submit” concluída/)).toBeVisible();await page.getByRole("button",{name:"Aprovar"}).click();await expect(page.getByText(/Ação “approve” concluída/)).toBeVisible();await page.getByRole("button",{name:"Publicar agora"}).click();await expect(page.getByText(/Ação “publish” concluída/)).toBeVisible();
  await page.goto(`/noticias/${slug}`);await expect(page.getByRole("heading",{name:new RegExp(`Notícia POC ${suffix}`)})).toBeVisible();

  await page.goto("/admin/diario");const edition=Number(suffix.slice(-5));await page.getByLabel("Número").fill(String(edition));await page.getByRole("button",{name:"Criar edição"}).click();await expect(page.getByText(/Edição criada em DRAFT/)).toBeVisible();await page.getByRole("button",{name:"Salvar composição"}).click();await expect(page.getByText(/Composição persistida/)).toBeVisible();await page.getByRole("button",{name:"Revisão"}).click();await page.getByRole("button",{name:"Aprovar"}).click();await page.getByRole("button",{name:"Gerar PDF"}).click();await expect(page.getByText(/Ação generate concluída/)).toBeVisible();await page.getByRole("button",{name:"Assinar"}).click();await expect(page.getByText(/NÃO possui valor de assinatura ICP-Brasil|Ação sign concluída/)).toBeVisible();await page.getByRole("button",{name:"Publicar"}).click();const verificationLink=page.getByRole("link",{name:/Abrir verificação pública/});await expect(verificationLink).toBeVisible();const href=await verificationLink.getAttribute("href");expect(href).toMatch(/^\/verificar\//);await page.goto(href!);await expect(page.getByText("Documento localizado")).toBeVisible();

  await page.goto("/ouvidoria");await page.getByLabel("Nome").fill("Pessoa Demonstração");await page.getByLabel("E-mail ou telefone").fill("poc@example.test");await page.getByLabel("Descrição").fill("Solicitação sintética criada pelo teste automatizado para validar protocolo e acompanhamento.");await page.getByRole("checkbox").check();await page.getByRole("button",{name:"Registrar manifestação"}).click();await expect(page.getByText("Manifestação registrada")).toBeVisible();await expect(page.getByText(/DEO-/)).toBeVisible();
});
