using System.Linq.Expressions;
using Microsoft.EntityFrameworkCore;
using MunicipalPlatform.Api.Modules.Content.Domain;
using MunicipalPlatform.Api.Modules.Gazette.Domain;
using MunicipalPlatform.Api.Modules.Identity.Domain;
using MunicipalPlatform.Api.Modules.Mail.Domain;
using MunicipalPlatform.Api.Modules.Media.Domain;
using MunicipalPlatform.Api.Modules.Migration.Domain;
using MunicipalPlatform.Api.Modules.Operations.Domain;
using MunicipalPlatform.Api.Modules.Platform.Domain;
using MunicipalPlatform.Api.Modules.Services.Domain;
using MunicipalPlatform.Api.Modules.Support.Domain;
using MunicipalPlatform.Api.Modules.Transparency.Domain;
using MunicipalPlatform.Api.Platform.Tenancy;

namespace MunicipalPlatform.Api.Infrastructure.Persistence;

public sealed class ApplicationDbContext(DbContextOptions<ApplicationDbContext> options, TenantContext tenantContext) : DbContext(options)
{
    public DbSet<NewsArticle> NewsArticles => Set<NewsArticle>(); public DbSet<PortalResource> PortalResources => Set<PortalResource>(); public DbSet<ContentRevision> ContentRevisions => Set<ContentRevision>(); public DbSet<GazetteEdition> GazetteEditions => Set<GazetteEdition>(); public DbSet<Municipality> Municipalities => Set<Municipality>(); public DbSet<UserAccount> Users => Set<UserAccount>(); public DbSet<RoleCapability> RoleCapabilities => Set<RoleCapability>(); public DbSet<Department> Departments => Set<Department>(); public DbSet<ServiceItem> Services => Set<ServiceItem>(); public DbSet<TransparencyLink> TransparencyLinks => Set<TransparencyLink>(); public DbSet<IntegrationStatus> IntegrationStatuses => Set<IntegrationStatus>(); public DbSet<AuditEvent> AuditEvents => Set<AuditEvent>(); public DbSet<OutboxMessage> OutboxMessages => Set<OutboxMessage>(); public DbSet<RedirectRule> RedirectRules => Set<RedirectRule>(); public DbSet<Ticket> Tickets => Set<Ticket>(); public DbSet<TicketComment> TicketComments => Set<TicketComment>(); public DbSet<SlaPolicy> SlaPolicies => Set<SlaPolicy>(); public DbSet<Mailbox> Mailboxes => Set<Mailbox>(); public DbSet<MediaAsset> MediaAssets => Set<MediaAsset>(); private Guid CurrentMunicipalityId => tenantContext.RequireMunicipalityId();
    public override int SaveChanges(bool acceptAllChangesOnSuccess) { EnforceTenantBoundary(); return base.SaveChanges(acceptAllChangesOnSuccess); }
    public override Task<int> SaveChangesAsync(bool acceptAllChangesOnSuccess, CancellationToken cancellationToken = default) { EnforceTenantBoundary(); return base.SaveChangesAsync(acceptAllChangesOnSuccess, cancellationToken); }
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        modelBuilder.Entity<NewsArticle>(e => { e.ToTable("news_articles"); e.HasKey(x => x.Id); e.Property(x => x.Title).HasMaxLength(180); e.Property(x => x.Slug).HasMaxLength(180); e.Property(x => x.Summary).HasMaxLength(320); e.Property(x => x.Body).HasColumnType("text"); e.Property(x => x.Status).HasConversion<string>().HasMaxLength(24); e.HasIndex(x => new { x.MunicipalityId, x.Slug }).IsUnique(); e.HasIndex(x => new { x.MunicipalityId, x.Status, x.PublishedAt }); });
        modelBuilder.Entity<PortalResource>(e => { e.ToTable("portal_resources"); e.HasKey(x => x.Id); e.Property(x => x.Kind).HasMaxLength(32); e.Property(x => x.Slug).HasMaxLength(180); e.Property(x => x.Title).HasMaxLength(220); e.Property(x => x.Summary).HasMaxLength(500); e.Property(x => x.PayloadJson).HasColumnType("jsonb"); e.Property(x => x.Status).HasMaxLength(24); e.HasIndex(x => new { x.MunicipalityId, x.Kind, x.Slug }).IsUnique(); e.HasIndex(x => new { x.MunicipalityId, x.Kind, x.Status, x.DisplayOrder }); });
        modelBuilder.Entity<ContentRevision>(e => { e.ToTable("content_revisions"); e.HasKey(x => x.Id); e.Property(x => x.ResourceKind).HasMaxLength(32); e.Property(x => x.SnapshotJson).HasColumnType("jsonb"); e.HasIndex(x => new { x.MunicipalityId, x.ResourceKind, x.ResourceId, x.CreatedAt }); });
        modelBuilder.Entity<GazetteEdition>(e => { e.ToTable("gazette_editions"); e.HasKey(x => x.Id); e.Property(x => x.Status).HasConversion<string>().HasMaxLength(24); e.Property(x => x.Type).HasConversion<string>().HasMaxLength(24); e.Property(x => x.CompositionJson).HasColumnType("text"); e.Property(x => x.Sha256).HasMaxLength(64); e.Property(x => x.VerificationCode).HasMaxLength(64); e.HasIndex(x => new { x.MunicipalityId, x.Year, x.Number }).IsUnique(); e.HasIndex(x => new { x.MunicipalityId, x.VerificationCode }).IsUnique(); });
        modelBuilder.Entity<Municipality>(e => { e.ToTable("municipalities"); e.HasKey(x => x.Id); e.Property(x => x.Name).HasMaxLength(160); e.Property(x => x.Slug).HasMaxLength(100); e.Property(x => x.StateCode).HasMaxLength(2); e.Property(x => x.PrimaryColor).HasMaxLength(32); e.HasIndex(x => x.Slug).IsUnique(); e.HasIndex(x => x.Domain).IsUnique(); });
        modelBuilder.Entity<UserAccount>(e => { e.ToTable("users"); e.HasKey(x => x.Id); e.Property(x => x.Username).HasMaxLength(100); e.Property(x => x.DisplayName).HasMaxLength(160); e.Property(x => x.Role).HasMaxLength(64); e.Property(x => x.PasswordHash).HasMaxLength(512); e.Property(x => x.MfaSecretProtected).HasMaxLength(4096); e.Property(x => x.MfaPendingSecretProtected).HasMaxLength(4096); e.HasIndex(x => new { x.MunicipalityId, x.Username }).IsUnique(); }); modelBuilder.Entity<RoleCapability>(e => { e.ToTable("role_capabilities"); e.HasKey(x => x.Id); e.Property(x => x.Role).HasMaxLength(64); e.Property(x => x.Capability).HasMaxLength(100); e.HasIndex(x => new { x.MunicipalityId, x.Role, x.Capability }).IsUnique(); });
        modelBuilder.Entity<Department>(e => { e.ToTable("departments"); e.HasKey(x => x.Id); e.HasIndex(x => new { x.MunicipalityId, x.Slug }).IsUnique(); }); modelBuilder.Entity<ServiceItem>(e => { e.ToTable("services"); e.HasKey(x => x.Id); e.Property(x => x.Description).HasColumnType("text"); e.Property(x => x.Requirements).HasColumnType("text"); e.Property(x => x.Documents).HasColumnType("text"); e.Property(x => x.Steps).HasColumnType("text"); e.HasIndex(x => new { x.MunicipalityId, x.Slug }).IsUnique(); e.HasIndex(x => new { x.MunicipalityId, x.Area, x.Status }); }); modelBuilder.Entity<TransparencyLink>(e => { e.ToTable("transparency_links"); e.HasKey(x => x.Id); e.HasIndex(x => new { x.MunicipalityId, x.Category, x.DisplayOrder }); });
        modelBuilder.Entity<IntegrationStatus>(e => { e.ToTable("integration_statuses"); e.HasKey(x => x.Id); e.Property(x => x.State).HasConversion<string>().HasMaxLength(24); e.HasIndex(x => new { x.MunicipalityId, x.Provider }).IsUnique(); }); modelBuilder.Entity<AuditEvent>(e => { e.ToTable("audit_events"); e.HasKey(x => x.Id); e.Property(x => x.SemanticDiff).HasColumnType("jsonb"); e.HasIndex(x => new { x.MunicipalityId, x.OccurredAt }); e.HasIndex(x => x.CorrelationId); }); modelBuilder.Entity<OutboxMessage>(e => { e.ToTable("outbox_messages"); e.HasKey(x => x.Id); e.Property(x => x.Type).HasMaxLength(120); e.Property(x => x.PayloadJson).HasColumnType("jsonb"); e.HasIndex(x => new { x.MunicipalityId, x.ProcessedAt, x.OccurredAt }); });
        modelBuilder.Entity<RedirectRule>(e => { e.ToTable("redirect_rules"); e.HasKey(x => x.Id); e.HasIndex(x => new { x.MunicipalityId, x.LegacyPath }).IsUnique(); }); modelBuilder.Entity<Ticket>(e => { e.ToTable("tickets"); e.HasKey(x => x.Id); e.Property(x => x.Priority).HasConversion<string>().HasMaxLength(16); e.Property(x => x.Description).HasColumnType("text"); e.HasIndex(x => new { x.MunicipalityId, x.Protocol }).IsUnique(); e.HasIndex(x => new { x.MunicipalityId, x.Status, x.ResolutionDueAt }); }); modelBuilder.Entity<TicketComment>(e => { e.ToTable("ticket_comments"); e.HasKey(x => x.Id); e.Property(x => x.Body).HasColumnType("text"); e.HasIndex(x => new { x.MunicipalityId, x.TicketId, x.CreatedAt }); }); modelBuilder.Entity<SlaPolicy>(e => { e.ToTable("sla_policies"); e.HasKey(x => x.Id); e.HasIndex(x => x.MunicipalityId).IsUnique(); }); modelBuilder.Entity<Mailbox>(e => { e.ToTable("mailboxes"); e.HasKey(x => x.Id); e.HasIndex(x => new { x.MunicipalityId, x.Address }).IsUnique(); }); modelBuilder.Entity<MediaAsset>(e => { e.ToTable("media_assets"); e.HasKey(x => x.Id); e.HasIndex(x => new { x.MunicipalityId, x.Sha256 }); e.HasIndex(x => new { x.MunicipalityId, x.Status, x.UploadedAt }); }); ApplyTenantFilters(modelBuilder);
    }
    private void EnforceTenantBoundary() { var id = tenantContext.RequireMunicipalityId(); var bad = ChangeTracker.Entries<ITenantEntity>().FirstOrDefault(entry => entry.State is EntityState.Added or EntityState.Modified or EntityState.Deleted && entry.Entity.MunicipalityId != id); if (bad is not null) throw new TenantPersistenceException($"A operação tentou alterar {bad.Metadata.ClrType.Name} de outro município."); }
    private void ApplyTenantFilters(ModelBuilder modelBuilder) { foreach (var type in modelBuilder.Model.GetEntityTypes().Where(t => typeof(ITenantEntity).IsAssignableFrom(t.ClrType))) { var p = Expression.Parameter(type.ClrType, "entity"); var municipality = Expression.Property(p, nameof(ITenantEntity.MunicipalityId)); var current = Expression.Property(Expression.Constant(this), nameof(CurrentMunicipalityId)); modelBuilder.Entity(type.ClrType).HasQueryFilter(Expression.Lambda(Expression.Equal(municipality, current), p)); } }
}
