using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using MunicipalPlatform.Api.Infrastructure.Persistence;
using MunicipalPlatform.Api.Modules.Administration;
using MunicipalPlatform.Api.Modules.Content;
using MunicipalPlatform.Api.Modules.Gazette;
using MunicipalPlatform.Api.Modules.Gazette.Providers;
using MunicipalPlatform.Api.Modules.Gazette.Services;
using MunicipalPlatform.Api.Modules.Identity;
using MunicipalPlatform.Api.Modules.Identity.Domain;
using MunicipalPlatform.Api.Modules.Mail;
using MunicipalPlatform.Api.Modules.Mail.Providers;
using MunicipalPlatform.Api.Modules.Media;
using MunicipalPlatform.Api.Modules.Media.Providers;
using MunicipalPlatform.Api.Modules.Migration;
using MunicipalPlatform.Api.Modules.Portal;
using MunicipalPlatform.Api.Modules.Support;
using MunicipalPlatform.Api.Platform.Observability;
using MunicipalPlatform.Api.Platform.Security;
using MunicipalPlatform.Api.Platform.Storage;
using MunicipalPlatform.Api.Platform.Tenancy;

var builder = WebApplication.CreateBuilder(args);
var databaseConnection = builder.Configuration.GetConnectionString("Database") ?? "Host=localhost;Port=5432;Database=municipal_platform;Username=municipal";
builder.Services.AddScoped<TenantContext>(); builder.Services.AddDbContext<ApplicationDbContext>(options => options.UseNpgsql(databaseConnection)); builder.Services.AddProblemDetails(); builder.Services.AddScoped<IPasswordHasher<UserAccount>, PasswordHasher<UserAccount>>(); builder.Services.AddSingleton<GazetteDocumentService>(); builder.Services.AddHostedService<ScheduledPublicationWorker>();
builder.Services.AddSingleton<IObjectStorageProvider>(services => { var env = services.GetRequiredService<IHostEnvironment>(); var config = services.GetRequiredService<IConfiguration>(); return env.IsDevelopment() || env.IsEnvironment("Testing") || config.GetValue<bool>("PresentationMode") ? new LocalObjectStorageProvider(config) : new NotConfiguredObjectStorageProvider(); });
builder.Services.AddSingleton<IDigitalSigner>(services => { var env = services.GetRequiredService<IHostEnvironment>(); var config = services.GetRequiredService<IConfiguration>(); return env.IsEnvironment("Testing") || config.GetValue<bool>("PresentationMode") ? new DemoDigitalSigner() : new NotConfiguredDigitalSigner(); }); builder.Services.AddSingleton<ICertificateProvider>(services => (ICertificateProvider)services.GetRequiredService<IDigitalSigner>()); builder.Services.AddSingleton<ISignatureValidator>(services => (ISignatureValidator)services.GetRequiredService<IDigitalSigner>()); builder.Services.AddSingleton<ITimestampProvider, NotConfiguredTimestampProvider>();
builder.Services.AddSingleton<IInstitutionalEmailProvider>(services => { var env = services.GetRequiredService<IHostEnvironment>(); var config = services.GetRequiredService<IConfiguration>(); return env.IsEnvironment("Testing") || config.GetValue<bool>("PresentationMode") ? new DemoInstitutionalEmailProvider() : new NotConfiguredInstitutionalEmailProvider(); }); builder.Services.AddSingleton<IMalwareScanner>(services => { var env = services.GetRequiredService<IHostEnvironment>(); var config = services.GetRequiredService<IConfiguration>(); return env.IsEnvironment("Testing") || config.GetValue<bool>("PresentationMode") ? new DemoMalwareScanner() : new NotConfiguredMalwareScanner(); });
builder.Services.AddEndpointsApiExplorer(); builder.Services.AddSwaggerGen(); builder.Services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme).AddCookie(options => { options.Cookie.Name = "municipal.session"; options.Cookie.HttpOnly = true; options.Cookie.SameSite = SameSiteMode.Lax; options.Cookie.SecurePolicy = builder.Environment.IsDevelopment() || builder.Environment.IsEnvironment("Testing") ? CookieSecurePolicy.SameAsRequest : CookieSecurePolicy.Always; options.Events.OnRedirectToLogin = context => { context.Response.StatusCode = 401; return Task.CompletedTask; }; options.Events.OnRedirectToAccessDenied = context => { context.Response.StatusCode = 403; return Task.CompletedTask; }; }); builder.Services.AddAuthorization();
var app = builder.Build(); if (!app.Environment.IsEnvironment("Testing")) await DatabaseInitializer.InitializeAsync(app.Services, app.Configuration, app.Environment); app.UseMiddleware<CorrelationIdMiddleware>(); app.UseMiddleware<SecurityHeadersMiddleware>(); app.UseExceptionHandler(); app.MapPlatformHealth(); if (app.Environment.IsDevelopment() || app.Environment.IsEnvironment("Testing")) { app.UseSwagger(); app.UseSwaggerUI(); } app.UseMiddleware<TenantResolutionMiddleware>(); app.UseMiddleware<LegacyRedirectMiddleware>(); app.UseAuthentication(); app.UseAuthorization(); app.MapIdentityEndpoints(); app.MapPortalEndpoints(); app.MapContentEndpoints(); app.MapResourceEndpoints(); app.MapSupportEndpoints(); app.MapGazetteEndpoints(); app.MapAdministrationEndpoints(); app.MapMailEndpoints(); app.MapMediaEndpoints(); app.MapMigrationEndpoints(); app.Run();
public partial class Program;
